In [1]:
import streamlit as st
api_key = st.secrets["API_KEY"]
print(api_key)

a74dcea8b8mshbc4d082460d16e2p1deaa3jsncaf6ab503fca

In [4]:
import requests

url = "https://alpha-vantage.p.rapidapi.com/query"
company = "State Bank of India"

querystring = {"datatype":"json","keywords":company,"function":"SYMBOL_SEARCH"}

headers = {
	"x-rapidapi-key": st.secrets["API_KEY"],
	"x-rapidapi-host": "alpha-vantage.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

data =response.json()
data

{'bestMatches': [{'1. symbol': 'SBIN.BSE',
   '2. name': 'State Bank of India',
   '3. type': 'Equity',
   '4. region': 'India/Bombay',
   '5. marketOpen': '09:15',
   '6. marketClose': '15:30',
   '7. timezone': 'UTC+5.5',
   '8. currency': 'INR',
   '9. matchScore': '1.0000'},
  {'1. symbol': 'SBKFF',
   '2. name': 'State Bank of India',
   '3. type': 'Equity',
   '4. region': 'United States',
   '5. marketOpen': '09:30',
   '6. marketClose': '16:00',
   '7. timezone': 'UTC-04',
   '8. currency': 'USD',
   '9. matchScore': '1.0000'},
  {'1. symbol': 'SID.FRK',
   '2. name': 'State Bank of India',
   '3. type': 'Equity',
   '4. region': 'Frankfurt',
   '5. marketOpen': '08:00',
   '6. marketClose': '20:00',
   '7. timezone': 'UTC+02',
   '8. currency': 'EUR',
   '9. matchScore': '1.0000'},
  {'1. symbol': 'SBID.LON',
   '2. name': 'State Bank of India GDR',
   '3. type': 'Equity',
   '4. region': 'United Kingdom',
   '5. marketOpen': '08:00',
   '6. marketClose': '16:30',
   '7. timezone': 'UTC+01',
   '8. currency': 'USD',
   '9. matchScore': '0.9048'}]}

In [5]:
import pandas as pd 
symbols = pd.DataFrame(data['bestMatches'])

In [6]:
symbols

,1. symbol,2. name,3. type,4. region,5. marketOpen,6. marketClose,7. timezone,8. currency,9. matchScore
0,SBIN.BSE,State Bank of India,Equity,India/Bombay,09:15,15:30,UTC+5.5,INR,1.0000
1,SBKFF,State Bank of India,Equity,United States,09:30,16:00,UTC-04,USD,1.0000
2,SID.FRK,State Bank of India,Equity,Frankfurt,08:00,20:00,UTC+02,EUR,1.0000
3,SBID.LON,State Bank of India GDR,Equity,United Kingdom,08:00,16:30,UTC+01,USD,0.9048

In [7]:
symbols.to_csv('symbols.csv', index=False)

In [8]:
import requests

url = "https://alpha-vantage.p.rapidapi.com/query"

symbol = "SBIN.BSE"


querystring = {"function":"TIME_SERIES_DAILY","symbol":symbol,"outputsize":"compact","datatype":"json"}

headers = {
	"x-rapidapi-key": st.secrets["API_KEY"],
	"x-rapidapi-host": "alpha-vantage.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

data = response.json()

In [9]:
data

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'SBIN.BSE',
  '3. Last Refreshed': '2026-01-09',
  '4. Output Size': 'Compact',
  '5. Time Zone': 'US/Eastern'},
 'Time Series (Daily)': {'2026-01-09': {'1. open': '996.9500',
   '2. high': '1008.0000',
   '3. low': '994.5500',
   '4. close': '1000.0000',
   '5. volume': '508305'},
  '2026-01-08': {'1. open': '1005.1500',
   '2. high': '1011.9000',
   '3. low': '995.6000',
   '4. close': '997.8500',
   '5. volume': '717133'},
  '2026-01-07': {'1. open': '1020.0500',
   '2. high': '1022.0000',
   '3. low': '1004.3000',
   '4. close': '1007.1000',
   '5. volume': '522691'},
  '2026-01-06': {'1. open': '1008.9000',
   '2. high': '1023.9500',
   '3. low': '1005.0000',
   '4. close': '1018.7500',
   '5. volume': '696022'},
  '2026-01-05': {'1. open': '1000.1000',
   '2. high': '1015.4000',
   '3. low': '1000.1000',
   '4. close': '1005.3500',
   '5. volume': '574850'},
  '2026-01-02': {'1. open': '984.7500',
   '2. high': '1009.3000',
   '3. low': '984.0500',
   '4. close': '999.3500',
   '5. volume': '489973'},
  '2026-01-01': {'1. open': '982.2000',
   '2. high': '987.7000',
   '3. low': '980.2000',
   '4. close': '984.7000',
   '5. volume': '848654'},
  '2025-12-31': {'1. open': '976.0000',
   '2. high': '985.4500',
   '3. low': '973.5500',
   '4. close': '982.2000',
   '5. volume': '332569'},
  '2025-12-30': {'1. open': '963.5500',
   '2. high': '976.0000',
   '3. low': '959.3500',
   '4. close': '973.3000',
   '5. volume': '340615'},
  '2025-12-29': {'1. open': '965.9500',
   '2. high': '968.3000',
   '3. low': '961.4500',
   '4. close': '964.8500',
   '5. volume': '326921'},
  '2025-12-26': {'1. open': '967.1000',
   '2. high': '971.1500',
   '3. low': '964.4500',
   '4. close': '966.4000',
   '5. volume': '401851'},
  '2025-12-24': {'1. open': '972.1000',
   '2. high': '977.5000',
   '3. low': '967.9500',
   '4. close': '969.0000',
   '5. volume': '406527'},
  '2025-12-23': {'1. open': '975.0500',
   '2. high': '977.6000',
   '3. low': '970.4500',
   '4. close': '971.8500',
   '5. volume': '181180'},
  '2025-12-22': {'1. open': '983.9000',
   '2. high': '983.9000',
   '3. low': '972.6000',
   '4. close': '974.2500',
   '5. volume': '395098'},
  '2025-12-19': {'1. open': '978.1500',
   '2. high': '981.9000',
   '3. low': '977.0000',
   '4. close': '980.1500',
   '5. volume': '261032'},
  '2025-12-18': {'1. open': '976.7500',
   '2. high': '981.0000',
   '3. low': '973.5000',
   '4. close': '977.7000',
   '5. volume': '594574'},
  '2025-12-17': {'1. open': '965.0000',
   '2. high': '978.5000',
   '3. low': '965.0000',
   '4. close': '975.9000',
   '5. volume': '569861'},
  '2025-12-16': {'1. open': '967.9500',
   '2. high': '969.0000',
   '3. low': '958.8000',
   '4. close': '961.4000',
   '5. volume': '222081'},
  '2025-12-15': {'1. open': '959.9500',
   '2. high': '969.3000',
   '3. low': '957.0500',
   '4. close': '967.1500',
   '5. volume': '118671'},
  '2025-12-12': {'1. open': '964.0500',
   '2. high': '967.0000',
   '3. low': '958.0000',
   '4. close': '962.9000',
   '5. volume': '205217'},
  '2025-12-11': {'1. open': '963.9500',
   '2. high': '966.4500',
   '3. low': '958.2500',
   '4. close': '963.4000',
   '5. volume': '1563506'},
  '2025-12-10': {'1. open': '959.3500',
   '2. high': '964.0000',
   '3. low': '955.1000',
   '4. close': '959.5500',
   '5. volume': '423587'},
  '2025-12-09': {'1. open': '956.0500',
   '2. high': '964.2000',
   '3. low': '950.8000',
   '4. close': '959.3500',
   '5. volume': '374212'},
  '2025-12-08': {'1. open': '972.3500',
   '2. high': '972.5000',
   '3. low': '951.0000',
   '4. close': '956.1000',
   '5. volume': '2120466'},
  '2025-12-05': {'1. open': '948.8000',
   '2. high': '972.8000',
   '3. low': '946.8000',
   '4. close': '971.4000',
   '5. volume': '511017'},
  '2025-12-04': {'1. open': '951.7000',
   '2. high': '952.5500',
   '3. low': '944.1000',
   '4. close': '948.0500',
   '5. volume': '2062068'},
  '2025-12-03': {'1. open': '972.2500',
   '2. high': '972.2500',
   '3. low': '947.3500',
   '4. close': '951.4000',
   '5. volume': '875186'},
  '2025-12-02': {'1. open': '976.0000',
   '2. high': '980.0500',
   '3. low': '964.5500',
   '4. close': '967.7500',
   '5. volume': '528774'},
  '2025-12-01': {'1. open': '984.7000',
   '2. high': '991.2500',
   '3. low': '970.2000',
   '4. close': '973.1500',
   '5. volume': '312355'},
  '2025-11-28': {'1. open': '977.0000',
   '2. high': '983.0000',
   '3. low': '973.0000',
   '4. close': '979.5500',
   '5. volume': '397881'},
  '2025-11-27': {'1. open': '987.8500',
   '2. high': '988.0000',
   '3. low': '968.8000',
   '4. close': '972.8500',
   '5. volume': '1490247'},
  '2025-11-26': {'1. open': '987.4000',
   '2. high': '999.1000',
   '3. low': '982.2000',
   '4. close': '984.0500',
   '5. volume': '412996'},
  '2025-11-25': {'1. open': '976.0000',
   '2. high': '988.9000',
   '3. low': '971.5000',
   '4. close': '983.2000',
   '5. volume': '243325'},
  '2025-11-24': {'1. open': '974.2000',
   '2. high': '977.8500',
   '3. low': '967.7000',
   '4. close': '970.3000',
   '5. volume': '444259'},
  '2025-11-21': {'1. open': '979.9500',
   '2. high': '980.5500',
   '3. low': '971.0000',
   '4. close': '972.6000',
   '5. volume': '188598'},
  '2025-11-20': {'1. open': '988.9500',
   '2. high': '988.9500',
   '3. low': '979.0000',
   '4. close': '981.7000',
   '5. volume': '1009998'},
  '2025-11-19': {'1. open': '972.5000',
   '2. high': '984.5000',
   '3. low': '969.0000',
   '4. close': '982.4500',
   '5. volume': '240778'},
  '2025-11-18': {'1. open': '976.8000',
   '2. high': '976.8000',
   '3. low': '970.0000',
   '4. close': '972.5500',
   '5. volume': '392640'},
  '2025-11-17': {'1. open': '974.1500',
   '2. high': '976.2000',
   '3. low': '969.9500',
   '4. close': '973.2000',
   '5. volume': '215607'},
  '2025-11-14': {'1. open': '954.2500',
   '2. high': '969.0000',
   '3. low': '953.0000',
   '4. close': '967.3500',
   '5. volume': '478259'},
  '2025-11-13': {'1. open': '955.7000',
   '2. high': '964.0000',
   '3. low': '952.2000',
   '4. close': '954.5500',
   '5. volume': '968319'},
  '2025-11-12': {'1. open': '958.0000',
   '2. high': '961.5000',
   '3. low': '951.0500',
   '4. close': '957.3500',
   '5. volume': '359053'},
  '2025-11-11': {'1. open': '954.0000',
   '2. high': '954.5000',
   '3. low': '945.0500',
   '4. close': '953.3000',
   '5. volume': '1406920'},
  '2025-11-10': {'1. open': '955.9500',
   '2. high': '963.0000',
   '3. low': '949.1500',
   '4. close': '951.8500',
   '5. volume': '387727'},
  '2025-11-07': {'1. open': '959.9500',
   '2. high': '964.5000',
   '3. low': '944.0000',
   '4. close': '955.9500',
   '5. volume': '582333'},
  '2025-11-06': {'1. open': '966.3500',
   '2. high': '971.1500',
   '3. low': '955.3000',
   '4. close': '960.7500',
   '5. volume': '1731058'},
  '2025-11-04': {'1. open': '952.2500',
   '2. high': '959.0000',
   '3. low': '941.3500',
   '4. close': '957.0500',
   '5. volume': '948033'},
  '2025-11-03': {'1. open': '938.5000',
   '2. high': '953.1500',
   '3. low': '937.8000',
   '4. close': '950.2500',
   '5. volume': '696733'},
  '2025-10-31': {'1. open': '935.8000',
   '2. high': '946.7000',
   '3. low': '930.2500',
   '4. close': '937.0000',
   '5. volume': '780748'},
  '2025-10-30': {'1. open': '940.0000',
   '2. high': '944.6000',
   '3. low': '932.9000',
   '4. close': '934.1000',
   '5. volume': '1338039'},
  '2025-10-29': {'1. open': '932.6000',
   '2. high': '941.6500',
   '3. low': '930.3000',
   '4. close': '939.8000',
   '5. volume': '1089247'},
  '2025-10-28': {'1. open': '923.2500',
   '2. high': '935.9000',
   '3. low': '917.8000',
   '4. close': '930.2500',
   '5. volume': '641738'},
  '2025-10-27': {'1. open': '905.5000',
   '2. high': '927.9000',
   '3. low': '905.5000',
   '4. close': '923.2500',
   '5. volume': '392249'},
  '2025-10-24': {'1. open': '911.4500',
   '2. high': '914.2000',
   '3. low': '900.8000',
   '4. close': '904.4000',
   '5. volume': '176431'},
  '2025-10-23': {'1. open': '910.5500',
   '2. high': '917.9000',
   '3. low': '904.8000',
   '4. close': '911.4500',
   '5. volume': '1321998'},
  '2025-10-20': {'1. open': '893.7000',
   '2. high': '913.4000',
   '3. low': '891.5500',
   '4. close': '906.8500',
   '5. volume': '835351'},
  '2025-10-17': {'1. open': '886.2500',
   '2. high': '894.6000',
   '3. low': '882.6000',
   '4. close': '889.3500',
   '5. volume': '436700'},
  '2025-10-16': {'1. open': '886.7500',
   '2. high': '891.9000',
   '3. low': '882.5000',
   '4. close': '886.9000',
   '5. volume': '1072968'},
  '2025-10-15': {'1. open': '877.2000',
   '2. high': '887.7500',
   '3. low': '877.2000',
   '4. close': '886.2000',
   '5. volume': '564545'},
  '2025-10-14': {'1. open': '883.0000',
   '2. high': '884.5000',
   '3. low': '872.1500',
   '4. close': '876.9000',
   '5. volume': '281465'},
  '2025-10-13': {'1. open': '879.9500',
   '2. high': '888.0500',
   '3. low': '875.8000',
   '4. close': '883.0000',
   '5. volume': '620211'},
  '2025-10-10': {'1. open': '861.2000',
   '2. high': '883.7000',
   '3. low': '861.2000',
   '4. close': '880.7500',
   '5. volume': '1334463'},
  '2025-10-09': {'1. open': '861.2500',
   '2. high': '865.6500',
   '3. low': '858.2500',
   '4. close': '862.1000',
   '5. volume': '1347934'},
  '2025-10-08': {'1. open': '866.1000',
   '2. high': '868.0000',
   '3. low': '857.3000',
   '4. close': '858.0500',
   '5. volume': '663817'},
  '2025-10-07': {'1. open': '874.0500',
   '2. high': '875.9500',
   '3. low': '863.0500',
   '4. close': '864.7000',
   '5. volume': '715720'},
  '2025-10-06': {'1. open': '868.9000',
   '2. high': '874.9000',
   '3. low': '862.5500',
   '4. close': '874.0500',
   '5. volume': '652683'},
  '2025-10-03': {'1. open': '864.1500',
   '2. high': '872.9500',
   '3. low': '863.8500',
   '4. close': '867.0500',
   '5. volume': '783340'},
  '2025-10-01': {'1. open': '872.6000',
   '2. high': '876.5000',
   '3. low': '862.4000',
   '4. close': '864.0500',
   '5. volume': '2208404'},
  '2025-09-30': {'1. open': '870.4500',
   '2. high': '877.5000',
   '3. low': '867.8500',
   '4. close': '872.5500',
   '5. volume': '229410'},
  '2025-09-29': {'1. open': '857.0500',
   '2. high': '873.0000',
   '3. low': '855.9000',
   '4. close': '870.5000',
   '5. volume': '533094'},
  '2025-09-26': {'1. open': '861.0500',
   '2. high': '864.1500',
   '3. low': '852.5000',
   '4. close': '857.0000',
   '5. volume': '342057'},
  '2025-09-25': {'1. open': '865.8500',
   '2. high': '870.0500',
   '3. low': '859.5500',
   '4. close': '861.0500',
   '5. volume': '804427'},
  '2025-09-24': {'1. open': '875.2000',
   '2. high': '880.4000',
   '3. low': '864.5500',
   '4. close': '865.8500',
   '5. volume': '450238'},
  '2025-09-23': {'1. open': '851.1000',
   '2. high': '874.0000',
   '3. low': '851.1000',
   '4. close': '870.5000',
   '5. volume': '388234'},
  '2025-09-22': {'1. open': '862.9000',
   '2. high': '868.0000',
   '3. low': '853.9000',
   '4. close': '855.0500',
   '5. volume': '266104'},
  '2025-09-19': {'1. open': '852.5000',
   '2. high': '863.5000',
   '3. low': '849.0500',
   '4. close': '862.2500',
   '5. volume': '552336'},
  '2025-09-18': {'1. open': '856.7000',
   '2. high': '860.9000',
   '3. low': '851.0500',
   '4. close': '854.4500',
   '5. volume': '719272'},
  '2025-09-17': {'1. open': '833.2500',
   '2. high': '858.0000',
   '3. low': '831.0000',
   '4. close': '856.9500',
   '5. volume': '1807341'},
  '2025-09-16': {'1. open': '823.4000',
   '2. high': '833.0000',
   '3. low': '821.6000',
   '4. close': '831.8000',
   '5. volume': '368364'},
  '2025-09-15': {'1. open': '823.3000',
   '2. high': '828.0000',
   '3. low': '821.4000',
   '4. close': '824.9000',
   '5. volume': '139666'},
  '2025-09-12': {'1. open': '824.9000',
   '2. high': '825.3500',
   '3. low': '819.9000',
   '4. close': '823.3000',
   '5. volume': '297096'},
  '2025-09-11': {'1. open': '816.2500',
   '2. high': '825.5000',
   '3. low': '816.2500',
   '4. close': '823.8000',
   '5. volume': '1044344'},
  '2025-09-10': {'1. open': '811.2000',
   '2. high': '824.5000',
   '3. low': '810.2000',
   '4. close': '818.3000',
   '5. volume': '489810'},
  '2025-09-09': {'1. open': '810.3500',
   '2. high': '812.4500',
   '3. low': '805.4000',
   '4. close': '808.9500',
   '5. volume': '170532'},
  '2025-09-08': {'1. open': '807.1000',
   '2. high': '813.5000',
   '3. low': '807.1000',
   '4. close': '809.0000',
   '5. volume': '268859'},
  '2025-09-05': {'1. open': '811.9000',
   '2. high': '812.2000',
   '3. low': '803.6000',
   '4. close': '806.9500',
   '5. volume': '272131'},
  '2025-09-04': {'1. open': '816.7500',
   '2. high': '816.7500',
   '3. low': '807.8500',
   '4. close': '809.3500',
   '5. volume': '619504'},
  '2025-09-03': {'1. open': '805.0000',
   '2. high': '813.2000',
   '3. low': '803.1000',
   '4. close': '812.1500',
   '5. volume': '187814'},
  '2025-09-02': {'1. open': '809.9000',
   '2. high': '810.5000',
   '3. low': '802.9000',
   '4. close': '803.9500',
   '5. volume': '119021'},
  '2025-09-01': {'1. open': '802.6500',
   '2. high': '808.2500',
   '3. low': '802.6500',
   '4. close': '805.9000',
   '5. volume': '164286'},
  '2025-08-29': {'1. open': '802.0000',
   '2. high': '807.0000',
   '3. low': '798.6000',
   '4. close': '802.3500',
   '5. volume': '520632'},
  '2025-08-28': {'1. open': '807.8000',
   '2. high': '810.6000',
   '3. low': '800.7000',
   '4. close': '802.0500',
   '5. volume': '146716'},
  '2025-08-26': {'1. open': '815.8000',
   '2. high': '815.8000',
   '3. low': '806.5500',
   '4. close': '807.8000',
   '5. volume': '677825'},
  '2025-08-25': {'1. open': '817.0000',
   '2. high': '820.4500',
   '3. low': '814.0000',
   '4. close': '815.5000',
   '5. volume': '373280'},
  '2025-08-22': {'1. open': '825.5000',
   '2. high': '825.9500',
   '3. low': '815.5500',
   '4. close': '816.1000',
   '5. volume': '158755'},
  '2025-08-21': {'1. open': '828.8000',
   '2. high': '833.4500',
   '3. low': '824.5000',
   '4. close': '825.5500',
   '5. volume': '138694'},
  '2025-08-20': {'1. open': '829.8000',
   '2. high': '831.5000',
   '3. low': '826.9500',
   '4. close': '828.8000',
   '5. volume': '156440'},
  '2025-08-19': {'1. open': '827.6500',
   '2. high': '831.2500',
   '3. low': '825.8500',
   '4. close': '830.3500',
   '5. volume': '289674'},
  '2025-08-18': {'1. open': '831.3500',
   '2. high': '835.2000',
   '3. low': '825.3000',
   '4. close': '827.0000',
   '5. volume': '435823'},
  '2025-08-14': {'1. open': '821.8500',
   '2. high': '828.0000',
   '3. low': '819.2000',
   '4. close': '826.7000',
   '5. volume': '492882'}}}

In [11]:
stock_df = pd.DataFrame(data['Time Series (Daily)']).T  
stock_df

              1. open    2. high     3. low   4. close 5. volume
2026-01-09   996.9500  1008.0000   994.5500  1000.0000    508305
2026-01-08  1005.1500  1011.9000   995.6000   997.8500    717133
2026-01-07  1020.0500  1022.0000  1004.3000  1007.1000    522691
2026-01-06  1008.9000  1023.9500  1005.0000  1018.7500    696022
2026-01-05  1000.1000  1015.4000  1000.1000  1005.3500    574850
...               ...        ...        ...        ...       ...
2025-08-21   828.8000   833.4500   824.5000   825.5500    138694
2025-08-20   829.8000   831.5000   826.9500   828.8000    156440
2025-08-19   827.6500   831.2500   825.8500   830.3500    289674
2025-08-18   831.3500   835.2000   825.3000   827.0000    435823
2025-08-14   821.8500   828.0000   819.2000   826.7000    492882

[100 rows x 5 columns]

In [12]:
stock_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 2026-01-09 to 2025-08-14
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   1. open    100 non-null    object
 1   2. high    100 non-null    object
 2   3. low     100 non-null    object
 3   4. close   100 non-null    object
 4   5. volume  100 non-null    object
dtypes: object(5)
memory usage: 4.7+ KB

In [13]:
stock_df= stock_df.astype(float)
stock_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 2026-01-09 to 2025-08-14
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   1. open    100 non-null    float64
 1   2. high    100 non-null    float64
 2   3. low     100 non-null    float64
 3   4. close   100 non-null    float64
 4   5. volume  100 non-null    float64
dtypes: float64(5)
memory usage: 4.7+ KB

In [14]:
stock_df.index

Index(['2026-01-09', '2026-01-08', '2026-01-07', '2026-01-06', '2026-01-05',
       '2026-01-02', '2026-01-01', '2025-12-31', '2025-12-30', '2025-12-29',
       '2025-12-26', '2025-12-24', '2025-12-23', '2025-12-22', '2025-12-19',
       '2025-12-18', '2025-12-17', '2025-12-16', '2025-12-15', '2025-12-12',
       '2025-12-11', '2025-12-10', '2025-12-09', '2025-12-08', '2025-12-05',
       '2025-12-04', '2025-12-03', '2025-12-02', '2025-12-01', '2025-11-28',
       '2025-11-27', '2025-11-26', '2025-11-25', '2025-11-24', '2025-11-21',
       '2025-11-20', '2025-11-19', '2025-11-18', '2025-11-17', '2025-11-14',
       '2025-11-13', '2025-11-12', '2025-11-11', '2025-11-10', '2025-11-07',
       '2025-11-06', '2025-11-04', '2025-11-03', '2025-10-31', '2025-10-30',
       '2025-10-29', '2025-10-28', '2025-10-27', '2025-10-24', '2025-10-23',
       '2025-10-20', '2025-10-17', '2025-10-16', '2025-10-15', '2025-10-14',
       '2025-10-13', '2025-10-10', '2025-10-09', '2025-10-08', '2025-10-07',
       '2025-10-06', '2025-10-03', '2025-10-01', '2025-09-30', '2025-09-29',
       '2025-09-26', '2025-09-25', '2025-09-24', '2025-09-23', '2025-09-22',
       '2025-09-19', '2025-09-18', '2025-09-17', '2025-09-16', '2025-09-15',
       '2025-09-12', '2025-09-11', '2025-09-10', '2025-09-09', '2025-09-08',
       '2025-09-05', '2025-09-04', '2025-09-03', '2025-09-02', '2025-09-01',
       '2025-08-29', '2025-08-28', '2025-08-26', '2025-08-25', '2025-08-22',
       '2025-08-21', '2025-08-20', '2025-08-19', '2025-08-18', '2025-08-14'],
      dtype='object')

In [15]:
stock_df.index  = pd.to_datetime(stock_df.index)    
stock_df.index

DatetimeIndex(['2026-01-09', '2026-01-08', '2026-01-07', '2026-01-06',
               '2026-01-05', '2026-01-02', '2026-01-01', '2025-12-31',
               '2025-12-30', '2025-12-29', '2025-12-26', '2025-12-24',
               '2025-12-23', '2025-12-22', '2025-12-19', '2025-12-18',
               '2025-12-17', '2025-12-16', '2025-12-15', '2025-12-12',
               '2025-12-11', '2025-12-10', '2025-12-09', '2025-12-08',
               '2025-12-05', '2025-12-04', '2025-12-03', '2025-12-02',
               '2025-12-01', '2025-11-28', '2025-11-27', '2025-11-26',
               '2025-11-25', '2025-11-24', '2025-11-21', '2025-11-20',
               '2025-11-19', '2025-11-18', '2025-11-17', '2025-11-14',
               '2025-11-13', '2025-11-12', '2025-11-11', '2025-11-10',
               '2025-11-07', '2025-11-06', '2025-11-04', '2025-11-03',
               '2025-10-31', '2025-10-30', '2025-10-29', '2025-10-28',
               '2025-10-27', '2025-10-24', '2025-10-23', '2025-10-20',
               '2025-10-17', '2025-10-16', '2025-10-15', '2025-10-14',
               '2025-10-13', '2025-10-10', '2025-10-09', '2025-10-08',
               '2025-10-07', '2025-10-06', '2025-10-03', '2025-10-01',
               '2025-09-30', '2025-09-29', '2025-09-26', '2025-09-25',
               '2025-09-24', '2025-09-23', '2025-09-22', '2025-09-19',
               '2025-09-18', '2025-09-17', '2025-09-16', '2025-09-15',
               '2025-09-12', '2025-09-11', '2025-09-10', '2025-09-09',
               '2025-09-08', '2025-09-05', '2025-09-04', '2025-09-03',
               '2025-09-02', '2025-09-01', '2025-08-29', '2025-08-28',
               '2025-08-26', '2025-08-25', '2025-08-22', '2025-08-21',
               '2025-08-20', '2025-08-19', '2025-08-18', '2025-08-14'],
              dtype='datetime64[ns]', freq=None)

In [16]:
stock_df

            1. open  2. high   3. low  4. close  5. volume
2026-01-09   996.95  1008.00   994.55   1000.00   508305.0
2026-01-08  1005.15  1011.90   995.60    997.85   717133.0
2026-01-07  1020.05  1022.00  1004.30   1007.10   522691.0
2026-01-06  1008.90  1023.95  1005.00   1018.75   696022.0
2026-01-05  1000.10  1015.40  1000.10   1005.35   574850.0
...             ...      ...      ...       ...        ...
2025-08-21   828.80   833.45   824.50    825.55   138694.0
2025-08-20   829.80   831.50   826.95    828.80   156440.0
2025-08-19   827.65   831.25   825.85    830.35   289674.0
2025-08-18   831.35   835.20   825.30    827.00   435823.0
2025-08-14   821.85   828.00   819.20    826.70   492882.0

[100 rows x 5 columns]

In [17]:
stock_df.to_csv('SBIN.csv', index=False)

In [ ]:
import plotly.graph_objects as go   
fig = go.Figure(data=[go.Candlestick(x=stock_df.index,
                open=stock_df['1. open'],
                high=stock_df['2. high'],
                low=stock_df['3. low'],
                close=stock_df['4. close']
                )
                ])

fig.show()

In [33]:

import streamlit as st
import requests
import pandas as pd
import plotly.graph_objects as go


class StockAPI:
    def __init__(self):
        self.url = "https://alpha-vantage.p.rapidapi.com/query"
        self.headers = {
	        "x-rapidapi-key": st.secrets["API_KEY"],
	        "x-rapidapi-host": "alpha-vantage.p.rapidapi.com"
        }
    def get_symbol(self, company:str) -> pd.DataFrame:
        querystring = {"datatype":"json","keywords":company,"function":"SYMBOL_SEARCH"}
        response = requests.get(self.url, headers=self.headers, params=querystring)
        response.raise_for_status()
        data =response.json()
        search_df = pd.DataFrame(data['bestMatches'])
        return search_df
    def get_daily_prices(self,symbol:str) -> pd.DataFrame:
        querystring = {"function":"TIME_SERIES_DAILY","symbol":symbol,"outputsize":"compact","datatype":"json"}
        response = requests.get(self.url, headers=self.headers, params=querystring)
        response.raise_for_status()
        data = response.json()
        price_df = pd.DataFrame(data['Time Series (Daily)']).T  
        price_df= price_df.astype(float)
        price_df.index  = pd.to_datetime(price_df.index)    
        return price_df
    def plot_candlestick(self, stock_df:pd.DataFrame) -> go.Figure:
        fig = go.Figure(data=[
            go.Candlestick(
                x=stock_df.index,
                open=stock_df['1. open'],
                high=stock_df['2. high'],
                low=stock_df['3. low'],
                close=stock_df['4. close']
                )
      ])
        fig.update_layout(
            height = 800,
            width = 1200
        )
        return fig

In [34]:
client = StockAPI()

In [35]:
client.get_symbol(company="HDFC Bank")

,1. symbol,2. name,3. type,4. region,5. marketOpen,6. marketClose,7. timezone,8. currency,9. matchScore
0,HDB,HDFC Bank Ltd,Equity,United States,09:30,16:00,UTC-04,USD,0.8182
1,HDFCBANK.BSE,HDFC Bank Limited,Equity,India/Bombay,09:15,15:30,UTC+5.5,INR,0.8000
2,0A7I.LON,HDFC Bank Limited,Equity,United Kingdom,08:00,16:30,UTC+01,USD,0.6923
3,H1DB34.SAO,HDFC Bank Limited,Equity,Brazil/Sao Paolo,10:00,17:30,UTC-03,BRL,0.6923
4,HDFA.FRK,HDFC Bank Limited,Equity,Frankfurt,08:00,20:00,UTC+02,EUR,0.6923

In [36]:
hdfc_prices = client.get_daily_prices(symbol="HDFCBANK.BSE")    
hdfc_prices

            1. open   2. high   3. low  4. close  5. volume
2026-01-09   946.45   950.350  933.200   938.700  1014507.0
2026-01-08   945.00   952.850  941.700   946.600  9669961.0
2026-01-07   957.20   957.600  946.000   949.150  7401483.0
2026-01-06   968.45   968.450  955.900   962.400  2306092.0
2026-01-05  1002.10  1006.300  976.350   977.700  1269360.0
...             ...       ...      ...       ...        ...
2025-08-21   998.90   998.900  991.700   995.100   574614.0
2025-08-20   993.00   996.200  989.750   994.000   638082.0
2025-08-19   999.00  1002.925  993.525   995.625  2029212.0
2025-08-18  1002.80  1012.925  997.725  1001.825   567152.0
2025-08-14   994.85   998.325  985.850   995.700   340592.0

[100 rows x 5 columns]

In [37]:
client.get_symbol("Godrej")

,1. symbol,2. name,3. type,4. region,5. marketOpen,6. marketClose,7. timezone,8. currency,9. matchScore
0,GODREJCP.BSE,GODREJ CONSUMER PRODUCTS LTD.,Equity,India/Bombay,09:15,15:30,UTC+5.5,INR,0.7059
1,GODREJIND.BSE,GODREJ INDUSTRIES LTD.,Equity,India/Bombay,09:15,15:30,UTC+5.5,INR,0.6667
2,GODREJAGRO.BSE,Godrej Agrovet Ltd,Equity,India/Bombay,09:15,15:30,UTC+5.5,INR,0.6316
3,GODREJPROP.BSE,Godrej Properties Ltd,Equity,India/Bombay,09:15,15:30,UTC+5.5,INR,0.6316
4,540743.BSE,Godrej Agrovet Limited,Equity,India/Bombay,09:15,15:30,UTC+5.5,INR,0.4286
5,532424.BSE,Godrej Consumer Products Limited,Equity,India/Bombay,09:15,15:30,UTC+5.5,INR,0.3158

In [38]:
fig = client.plot_candlestick(hdfc_prices)
fig.show()

In [39]:
fig = client.plot_candlestick(hdfc_prices)
fig.show()